# Generated by Django 5.2.7 on 2025-10-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('args_and_kwargs', models.JSONField()),
                ('error', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('ERROR', 'Error')], default='NEW', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'djjp_job',
            },
        ),
        migrations.CreateModel(
            name='LockedJob',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'djjp_locked_job',
            },
        ),
    ]
