# Generated by Django 5.2.7 on 2025-10-26 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('args_and_kwargs', models.JSONField()),
                ('error', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('BLOCKED', 'Blocked'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('ERROR', 'Error')], default='NEW', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_step', models.UUIDField(blank=True, null=True)),
                ('step', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'djjp_job',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LockedJob',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='django_async_job_pipelines.jobdbmodel')),
            ],
            options={
                'db_table': 'djjp_locked_job',
            },
        ),
        migrations.AddField(
            model_name='jobdbmodel',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_async_job_pipelines.manager'),
        ),
    ]
