# Generated by Django 5.2.7 on 2025-10-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_async_job_pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobdbmodel',
            index=models.Index(fields=['status'], name='djjp_job_status_076360_idx'),
        ),
    ]
