# Generated by Django 5.2.7 on 2025-10-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_async_job_pipelines', '0002_jobdbmodel_djjp_job_status_076360_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lockedjob',
            index=models.Index(fields=['job'], name='djjp_locked_job_id_c91c29_idx'),
        ),
    ]
