# Generated by Django 5.2.7 on 2025-10-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_async_job_pipelines', '0003_lockedjob_djjp_locked_job_id_c91c29_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobdbmodel',
            index=models.Index(fields=['step'], name='djjp_job_step_b3fab5_idx'),
        ),
    ]
